version: "3.7"

services:

  openldap:
    image: "osixia/phpldapadmin:latest"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openldap.rule=Path(`/openldap`)||PathPrefix(`/openldap/`)"
      - "traefik.http.routers.openldap.entrypoints=web"
      - "traefik.http.services.openldap-admin.loadbalancer.server.port=80"
      - "traefik.http.services.openldap-admin.loadbalancer.server.scheme=http"
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: server
      PHPLDAPADMIN_HTTPS: 'false'
    volumes:
      - admin:/var/www/phpldapadmin
    ports:
      - "8100:80"
    networks:
      - external

volumes:
  admin:

networks:
  external:
    external: true
